### ISSUE TITLE
The sample code for the listening server doesn't work because.....

### ISSUE THREAD

**Issue by anonymous-d0z42ujxuog5** [peterpeerdeman/growatt-data-parser#1]
_The contents of this message was removed by the author_

**Comment by peterpeerdeman** [comment]
Hi anonymous, thank you so much for your reply and elaborate fix explanaition! I'm terribly sorry for my late reply, I missed the notification for this issue before. You are completely right, and in addition to the different packet sizes the growatt module also expects to hear ACK messages coming back from the server. 

I've recently picked up the project again and have patched the issues. I have made a major upgrade in which I don't throw "wrong size" errors anymore but now detect the serial number and read the values from there. With an extra check I also omit giving bad results when you feed the library an ANNOUNCE package. 

I hope this update (version 2.1.0) fixes your problem, and please have a look at https://github.com/peterpeerdeman/raspsolar to see how I wrote the server code that uses this library and will also respond to the growatt module with the right ACK messages =)

feel free to reply / reopen if your issue is not fixed yet.
